Tensorboard plugin
isl-org/Open3D-ML pull request #405
Opened 2021-10-31 18:54 UTC by ssheorey

Summary writing support for all models (except KPConv) for both PyTorch and TF.
Address pylint warnings / errors in pipeline files (TF + PyTorch)
### WIP: 

- [ ] Testing 
- [ ] Order of label names for ScanNet

2021-11-01 19:04 UTC, ssheorey commented on ml3d/torch/pipelines/semantic_segmentation.py
> +                    if 'valid' in record_summary and step == 0:
Let's standardize on one word for this  -- different words in different places for the same functionality creates user confusion. We have different words currently. We should remove them in a future PR. Similar for `train` (not `training`) and `test` (not `testing`).

2021-11-01 19:23 UTC, ssheorey commented on ml3d/torch/pipelines/semantic_segmentation.py
> +        record_summary = cfg.get('summary').get('record_for', [])
Added `self.cfg.setdefault('summary', {})` in `base_pipeline.py`  `__init__()` so that there is an empty dict if not provided

2021-11-10 10:30 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/405)* status: 0 of 35 files reviewed, 5 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[ml3d/tf/pipelines/semantic_segmentation.py, line 317 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8NVR0E8nzzD-MZ77H:-Mo8NVR0E8nzzD-MZ77I:b-j29yen) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/tf/pipelines/semantic_segmentation.py#L317)):*
> ```Python
>                 self.save_ckpt(epoch)
> 
>     def get_3d_summary(self, results, input_data, epoch, save_gt=True):
> ```

just a question. Would it be possible to unify the tf and torch code by converting early to numpy? Would it make sense to use numpy?
___
*[ml3d/vis/boundingbox.py, line 83 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8KJRh5ZGqZivMmOvD:-Mo8KJRh5ZGqZivMmOvE:b-j7ekhc) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/vis/boundingbox.py#L83)):*
> ```Python
> 
>     @staticmethod
>     def create_lines(boxes, lut=None, out="lineset"):
> ```

`out -> out_format or format`. `out` could be mistaken for an output variable like it is used in many numpy functions.
___
*[ml3d/vis/boundingbox.py, line 99 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8MNsiBhZQpBjDl461:-Mo8MNsiBhZQpBjDl462:bt0ryb9) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/vis/boundingbox.py#L99)):*
> ```Python
>                 "line_indices", "line_colors", "bbox_labels",
>                 "bbox_confidences") if out == "dict".
>         """
> ```

check output format here to provide a better error message.


<!-- Sent from Reviewable.io -->

2021-11-11 01:10 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/405)* status: 0 of 35 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[ml3d/tf/pipelines/semantic_segmentation.py, line 317 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8NVR0E8nzzD-MZ77H:-MoBU0NB3LGtoPyvnKNE:b7dh51u) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/tf/pipelines/semantic_segmentation.py#L317)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

just a question. Would it be possible to unify the tf and torch code by converting early to numpy? Would it make sense to use numpy?
</blockquote></details>

The models themselves have different representations for data, even in TF vs Torch. I don't think we'll be able to share code this way. The underlying `add_3d()` function works with any of TF, Torch, Numpy and Open3D tensors and converts everything to Open3D tensors for writing.
___
*[ml3d/vis/boundingbox.py, line 83 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8KJRh5ZGqZivMmOvD:-MoBWDP00edHf-YaT_jv:bb40hdc) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/vis/boundingbox.py#L83)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

`out -> out_format or format`. `out` could be mistaken for an output variable like it is used in many numpy functions.
</blockquote></details>

Done. This needs a corresponding change to `summary.py` in the main repo. It will be in the `ssheorey/tb-plugin-docs` branch.
___
*[ml3d/vis/boundingbox.py, line 99 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/405#-Mo8MNsiBhZQpBjDl461:-MoBWCfB0dO0DwL8i0SQ:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/772e8f174165237e6733a1b72e44a744a8a924e5/ml3d/vis/boundingbox.py#L99)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

check output format here to provide a better error message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 08:49 UTC, benjaminum reviewed
from my side this looks good

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/405#-:-MoXlyJvANXAWg4ZpJ7M:b1r18kl)* status: 0 of 39 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @sanskar107)



<!-- Sent from Reviewable.io -->

2021-11-15 14:49 UTC, sanskar107 approved these changes

2021-11-15 22:01 UTC, merged